package release

// Code generated by scripts/update-release-amis.sh. DO NOT EDIT.

var awsAMIs = map[string]map[string]string{
	"ap-southeast-1": {
		"amd64": "ami-030fc637ef07f4622",
		"arm64": "ami-08c81e496c454d276",
	},
	"eu-central-1": {
		"amd64": "ami-0cf1d90115e7ea4dd",
		"arm64": "ami-0b274b2fd5218da7c",
	},
	"eu-west-1": {
		"amd64": "ami-005abb2af342d5b27",
		"arm64": "ami-0287c0578b9d9a36d",
	},
	"us-east-1": {
		"amd64": "ami-0f0c5fca374fb0116",
		"arm64": "ami-0c935653e9dabb2e9",
	},
	"us-west-2": {
		"amd64": "ami-0157bda714a8b2824",
		"arm64": "ami-02c5ba9d92356bccd",
	},
}
