package release

// Code generated by scripts/update-release-amis.sh. DO NOT EDIT.

var awsAMIs = map[string]map[string]string{
	"us-east-1": {
		"amd64": "ami-0ad702844e8800bc5",
		"arm64": "ami-056ad0fed597c6c83",
	},
}
