#!/usr/bin/env bash
set -euo pipefail

output="internal/release/amis.go"

usage() {
  cat <<'EOF'
Usage: scripts/update-release-amis.sh --manifest-amd64 <path> --manifest-arm64 <path> [--output <path>]

Parses Packer manifest files (which contain multi-region artifact IDs) and
rewrites the committed Forja release AMI map used by `forja init`.

The Packer artifact_id format for multi-region builds is:
  region1:ami-xxx,region2:ami-yyy,...

Options:
  --manifest-amd64 <path>  Path to the amd64 Packer manifest JSON.
  --manifest-arm64 <path>  Path to the arm64 Packer manifest JSON.
  --output <path>          Output Go file (default: internal/release/amis.go).
  --help                   Show this help text.
EOF
}

manifest_amd64=""
manifest_arm64=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --manifest-amd64)
      manifest_amd64="${2:?missing value for --manifest-amd64}"
      shift 2
      ;;
    --manifest-arm64)
      manifest_arm64="${2:?missing value for --manifest-arm64}"
      shift 2
      ;;
    --output)
      output="${2:?missing value for --output}"
      shift 2
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ -z "${manifest_amd64}" || -z "${manifest_arm64}" ]]; then
  usage >&2
  exit 1
fi

for f in "${manifest_amd64}" "${manifest_arm64}"; do
  if [[ ! -f "${f}" ]]; then
    echo "manifest file not found: ${f}" >&2
    exit 1
  fi
done

# Parse artifact_id from a Packer manifest. The last build entry contains the
# artifact_id in the format "region1:ami-xxx,region2:ami-yyy".
parse_artifact_id() {
  jq -r '.builds[-1].artifact_id' "$1"
}

amd64_artifacts=$(parse_artifact_id "${manifest_amd64}")
arm64_artifacts=$(parse_artifact_id "${manifest_arm64}")

# Collect all regions from both manifests.
declare -A amd64_map
declare -A arm64_map

IFS=',' read -ra amd64_pairs <<< "${amd64_artifacts}"
for pair in "${amd64_pairs[@]}"; do
  region="${pair%%:*}"
  ami="${pair##*:}"
  amd64_map["${region}"]="${ami}"
done

IFS=',' read -ra arm64_pairs <<< "${arm64_artifacts}"
for pair in "${arm64_pairs[@]}"; do
  region="${pair%%:*}"
  ami="${pair##*:}"
  arm64_map["${region}"]="${ami}"
done

# Build sorted list of regions.
regions=()
for region in "${!amd64_map[@]}"; do
  regions+=("${region}")
done
IFS=$'\n' sorted_regions=($(sort <<< "${regions[*]}")); unset IFS

# Generate Go source.
{
  cat <<'GOHEADER'
package release

// Code generated by scripts/update-release-amis.sh. DO NOT EDIT.

var awsAMIs = map[string]map[string]string{
GOHEADER

  for region in "${sorted_regions[@]}"; do
    amd64="${amd64_map[${region}]:-}"
    arm64="${arm64_map[${region}]:-}"
    if [[ -z "${amd64}" || -z "${arm64}" ]]; then
      echo "warning: region ${region} missing an architecture AMI" >&2
      continue
    fi
    printf '\t"%s": {\n' "${region}"
    printf '\t\t"amd64": "%s",\n' "${amd64}"
    printf '\t\t"arm64": "%s",\n' "${arm64}"
    printf '\t},\n'
  done

  echo "}"
} > "${output}"

if command -v gofmt >/dev/null 2>&1; then
  gofmt -w "${output}"
fi

echo "Wrote AMI map to ${output}:"
cat "${output}"
