#!/usr/bin/env bash
set -euo pipefail

output="internal/release/amis.go"
region=""
amd64_ami=""
arm64_ami=""

usage() {
  cat <<'EOF'
Usage: scripts/update-release-amis.sh --region <region> --amd64-ami <ami> --arm64-ami <ami> [--output <path>]

Rewrites the committed Forja release AMI map used by `forja init`.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --region)
      region="${2:?missing value for --region}"
      shift 2
      ;;
    --amd64-ami)
      amd64_ami="${2:?missing value for --amd64-ami}"
      shift 2
      ;;
    --arm64-ami)
      arm64_ami="${2:?missing value for --arm64-ami}"
      shift 2
      ;;
    --output)
      output="${2:?missing value for --output}"
      shift 2
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ -z "${region}" || -z "${amd64_ami}" || -z "${arm64_ami}" ]]; then
  usage >&2
  exit 1
fi

case "${amd64_ami}" in
  ami-*) ;;
  *)
    echo "invalid amd64 AMI: ${amd64_ami}" >&2
    exit 1
    ;;
esac

case "${arm64_ami}" in
  ami-*) ;;
  *)
    echo "invalid arm64 AMI: ${arm64_ami}" >&2
    exit 1
    ;;
esac

cat >"${output}" <<EOF
package release

// Code generated by scripts/update-release-amis.sh. DO NOT EDIT.

var awsAMIs = map[string]map[string]string{
	"${region}": {
		"amd64": "${amd64_ami}",
		"arm64": "${arm64_ami}",
	},
}
EOF

if command -v gofmt >/dev/null 2>&1; then
  gofmt -w "${output}"
fi
